### ISSUE TITLE
Set up React Router Type Safety

### ISSUE THREAD

**Issue by aedwardg** [CodeCafeCommunity/codecafecommunity.github.io#22]
We aren't using React Router for any routes yet, but once we do we'll probably want type safety on those routes.
Setting that up should be fairly straightforward.
See the setup guide [here](https://reactrouter.com/how-to/route-module-type-safety) and the docs on it [here](https://reactrouter.com/explanation/type-safety).

Note: This is blocked by #21. Either wait for that PR to be merged or branch off of that feature branch to start work on this ticket.

**Comment by Jamesllllllllll** [comment]
I'll take this on. I have it scaffolded locally, but currently struggling to have types generated with running `react-router dev` to generate types.

**Comment by Jamesllllllllll** [comment]
The branch if anyone wants to take a look. I will continue working on it later.

https://github.com/CodeCafeCommunity/codecafecommunity.github.io/tree/enhancement/react-router-type-safety

**Comment by Jamesllllllllll** [comment]
When running `npm run typecheck` there is an error:

```shell
Error: Could not find a root route module in the app directory as "app/root.tsx" at createConfigLoader
```

It's looking for the `/app` directory, which makes me thing this might only work when using React Router as a framework rather than a library.

I tried renaming `/src` to app, and `/main.tsx` to `/root.tsx` to no avail, `typecheck` is looking for the framework application structure.

**Comment by aedwardg** [comment]
Upon further investigation and discussion, we decided to not worry about type safe routes because setting them up is more trouble than it's worth.
See the [discord thread](https://discord.com/channels/605859344243884081/1322429475933130812) for details
