### ISSUE TITLE
Add PR and Issue templates

### ISSUE THREAD

**Issue by aedwardg** [CodeCafeCommunity/codecafecommunity.github.io#4]
It's easier for contributors to work if we have Issue and PR templates already set up.
Follow docs [here](https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/about-issue-and-pull-request-templates) and get some initial templates set up for the Repo.

**Comment by ashstewart7** [comment]
Bumping the ones we used on the old project [here](https://github.com/CodecademyCommunity/CodecademyCommunity.github.io/tree/main/.github) as a starting point perhaps, they worked nicely.

**Comment by aedwardg** [comment]
Agreed. One other thing that might be nice to add to PR template is a section that says "If you made UI changes, please include a screenshot of those changes". This can help facilitate faster review turnaround if reviewers don't have time to pull down the branch and see the changes themselves.
