### ISSUE TITLE
Add license to the project

### ISSUE THREAD

**Issue by aedwardg** [CodeCafeCommunity/codecafecommunity.github.io#8]
Probably MIT?
Docs [here](https://docs.github.com/en/communities/setting-up-your-project-for-healthy-contributions/adding-a-license-to-a-repository)

**Comment by Victoria-DR** [comment]
I prefer ISC since it's shorter, but the 2 are functionally the same.

**Comment by Jamesllllllllll** [comment]
I also like the ISC license for brevity. Created above PR but please feel free to discuss before merging.
